### ISSUE TITLE
Making private and creating users

### ISSUE THREAD

**Issue by VideahGams** [linuxserver/docker-thelounge#1]
How would I go about setting this to private and creating a user?

**Comment by iPonyRadio** [comment]
Well, setting it private is pretty easy - just change the config.json. It's in your config mountpoint

**Comment by iPonyRadio** [comment]
I'm still trying to figure out exactly where in the docker install the `lounge` command is stored, because it's not in the $PATH

**Comment by VideahGams** [comment]
I figured it out, it's in `/app/node_modules/.bin`
It doesn't create new users in the right place however, you need to move it from
`/root/.lounge/users` to `/config/users`

**Comment by sparklyballs** [comment]
it might need a HOME environment setting for /config

**Comment by iPonyRadio** [comment]
`node /app/node_modules/thelounge/index.js --home /config add <user>`
